### ISSUE TITLE
Can you provide Chinese version?

### ISSUE THREAD

**Issue by KingBes** [malisipi/VInstall#4]

**Comment by malisipi** [comment]
I will add Chinese language support however I am busy for a week due to university entrance exam.

**Comment by malisipi** [comment]
Chinese support is added by e9b909c2d816ae4379a280f9e4e53938d5628705. Since chinese font should be embedded to installer, the choose was given to developer. To enable support, you need to pass `-d extended_language_support` flag to V.

A example of Chinese support on Linux that has not a system font that support Chinese.
![resim](https://github.com/malisipi/VInstall/assets/87281783/bf59ca99-24fd-4b1d-bbbb-759b898b4cc3)

**Comment by KingBes** [comment]
thanks
